# Generated by Django 5.2.1 on 2025-07-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0003_child_birth_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='vaccination_card',
            field=models.FileField(blank=True, null=True, upload_to='vaccination_cards/'),
        ),
    ]
