# Generated by Django 5.2.1 on 2025-07-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0002_user_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='birth_certificates/'),
        ),
    ]
