# Generated by Django 4.2.7 on 2025-08-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0007_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='child_age_months',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='application',
            name='role_applied',
        ),
        migrations.AddField(
            model_name='application',
            name='child_birth_date',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='employee_monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='kebele',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='spouse_monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='sub_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='woreda',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
